// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AuthorizationRequest {
    #[prost(string, tag = "1")]
    pub uuid: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub code: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub category: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub target_os: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Authentication {
    #[prost(string, tag = "1")]
    pub app_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub app_secret: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecuteCliCommandRequest {
    #[prost(string, tag = "1")]
    pub command: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub arguments: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "3")]
    pub request_unique_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ExecuteCliCommandResponse {
    #[prost(string, tag = "1")]
    pub stdout: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub stderr: ::prost::alloc::string::String,
    #[prost(int32, tag = "3")]
    pub status: i32,
    #[prost(string, tag = "4")]
    pub request_unique_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClientMessage {
    #[prost(oneof = "client_message::Message", tags = "1, 2, 3, 4")]
    pub message: ::core::option::Option<client_message::Message>,
}
/// Nested message and enum types in `ClientMessage`.
pub mod client_message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Message {
        #[prost(message, tag = "1")]
        AuthorizationRequest(super::AuthorizationRequest),
        #[prost(message, tag = "2")]
        Authentication(super::Authentication),
        #[prost(message, tag = "3")]
        ExecuteCliCommandResponse(super::ExecuteCliCommandResponse),
        #[prost(message, tag = "4")]
        Heartbeat(()),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AuthenticationData {
    #[prost(string, optional, tag = "1")]
    pub app_id: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "2")]
    pub app_secret: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SshSessionData {
    #[prost(string, tag = "1")]
    pub tunnel_token: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub public_key: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UiSessionData {
    #[prost(string, tag = "1")]
    pub tunnel_token: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub local_addr: ::prost::alloc::string::String,
    #[prost(uint32, tag = "3")]
    pub local_port: u32,
    #[prost(string, tag = "4")]
    pub protocol: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerMessage {
    #[prost(
        oneof = "server_message::Message",
        tags = "1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15"
    )]
    pub message: ::core::option::Option<server_message::Message>,
}
/// Nested message and enum types in `ServerMessage`.
pub mod server_message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Message {
        #[prost(string, tag = "1")]
        UpdateTokenCommand(::prost::alloc::string::String),
        #[prost(bool, tag = "2")]
        EnableNetworkMonitoringCommand(bool),
        #[prost(bool, tag = "3")]
        EnableConfigurationMonitoringCommand(bool),
        #[prost(bool, tag = "4")]
        EnableTelemetryMonitoringCommand(bool),
        #[prost(message, tag = "5")]
        OpenSshSessionCommand(super::SshSessionData),
        #[prost(string, tag = "6")]
        OpenTtySessionCommand(::prost::alloc::string::String),
        #[prost(message, tag = "7")]
        OpenUiSessionCommand(super::UiSessionData),
        #[prost(string, tag = "8")]
        OpenRemoteDesktopSessionCommand(::prost::alloc::string::String),
        #[prost(message, tag = "9")]
        DeviceAuthorizedMessage(super::AuthenticationData),
        #[prost(message, tag = "10")]
        DeviceDeauthorizedMessage(()),
        #[prost(message, tag = "11")]
        AuthorizationRejectedMessage(()),
        #[prost(message, tag = "12")]
        CreateFilterRule(super::super::wallguard_models::FilterRule),
        #[prost(message, tag = "13")]
        CreateNatRule(super::super::wallguard_models::NatRule),
        #[prost(message, tag = "14")]
        CreateAlias(super::super::wallguard_models::Alias),
        #[prost(message, tag = "15")]
        ExecuteCliCommandRequest(super::ExecuteCliCommandRequest),
    }
}
