name: WallMon Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential libcunit1-dev valgrind

    - name: Build
      run: make test

    - name: Run tests
      run: valgrind --leak-check=full --error-exitcode=1 ./wallmon_test
